server:
  port: 20000
#    整合Spring Session 过期时间
  servlet:
    session:
      timeout: 30m
spring:
  cloud:
    #Nacos 注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #配置sentinel
    sentinel:
      transport:
        dashboard: localhost:8080
        #控制台的port
        port: 8719
    #日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    关闭thymeleaf缓存 开发期间就能看到实时效果；上线以后就要打开缓存了(效果不大)
  thymeleaf:
    cache: false
#    cache: true
#    配置Redis缓存
  redis:
    host: 10.211.55.3
    port: 6379
#    整合Spring Session 指定session是存到redis里
  session:
    store-type: redis
#logging:
#  level:
#    #上线后，可以降低日志级别
##    com.atguigu.gulimall: debuug
#    com.atguigu.gulimall: error

#management.endpoints.web.exposure.include=*
#配置actuator统计审计信息 配合sentinel
management:
  endpoints:
    web:
      exposure:
        include: all