spring:
#      Nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  #    关闭thymeleaf缓存 开发期间就能看到实时效果；上线以后就要打开缓存了(效果不大)
  thymeleaf:
    cache: false
#    cache: true
logging:
  level:
    com.atguigu.gulimall: debug
server:
  port: 12000
