spring:
#      Nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search

logging:
  level:
    com.atguigu.gulimall: debug
server:
  port: 12000
